function search_db_content(){ var json = 
[
  {
    "id": 1,
    "title": "Registrieren",
    "url": "284567.htm",
    "text": "Registrieren Sie sich im Product Compatibility and Download Center, um Aktualisierungen zu erhalten.  Um Rockwell Automation-Produkt-Aktualisierungen f\u00fcr die Firmware zu erhalten und Patch-Roll-ups direkt herunterzuladen, navigieren Sie zum Product Compatibility and Download Center. Klicken Sie auf das Symbol @ Subscriptions, um Benachrichtigungen zu bestimmten Produkten zu erhalten.  Registrieren Sie sich, um Aktualisierungen der Wissensdatenbank zu erhalten  Die Wissensdatenbank von Rockwell Automation bietet zus\u00e4tzliche Informationen zu den neuesten Produktaktualisierungen und Patches.  Um Benachrichtigungen zu bestimmten Produkten zu erhalten, folgen Sie den Anweisungen in der Knowledgebase-Dokument-ID: PN27 - Subscribing to Product Safety Advisory (PSA) or Product Notice (PN) Notifications.  Um eine E-Mail-Benachrichtigung zu erhalten, wenn die Produkten und Patches aktualisiert werden, w\u00e4hlen Sie im oberen Bereich in der Knowledgebase-Dokument-ID: Subscribe to Updates : QA57432 - Hauptliste der verf\u00fcgbaren Patch-TOCs.  Weitere Informationen finden Sie unter  Rechtliche Hinweise  "
  },
  {
    "id": 2,
    "title": "Rechtliche Hinweise",
    "url": "196866.htm",
    "text": "Urheberrechtshinweis  Copyright &copy; 2020 Rockwell Automation Technologies, Inc. Alle Rechte vorbehalten. Gedruckt in den USA.  Dieses Dokument und dazugeh\u00f6rige Rockwell Software-Produkte sind urheberrechtlich durch Rockwell Automation Technologies, Inc. gesch\u00fctzt. Jegliche Vervielf\u00e4ltigung und/oder Weitergabe ohne vorherige schriftliche Zustimmung durch Rockwell Automation Technologies, Inc. ist strengstens untersagt. N\u00e4here Informationen k\u00f6nnen Sie der Lizenzvereinbarung entnehmen.  Endbenutzer-Lizenzvereinbarung (EULA)  Die Rockwell Automation Endbenutzer-Lizenzvereinbarung (\"EULA\") befindet sich in der Datei \"License.rtf\" im Installationsverzeichnis des Produkts auf Ihrer Festplatte.  Sonstige Lizenzen  FieldCare SFE500 ist von der Endress + Hauser AG  Markenhinweise  Allen-Bradley, Rockwell Automation und Rockwell Software sind Marken von Rockwell Automation, Inc.  Alle Rockwell Automation Software- oder Hardware-Produkte, die hier nicht erw\u00e4hnt werden, sind ebenfalls Marken, eingetragen oder anderweitig zu Rockwell Automation, Inc. zugeh\u00f6rig.  Weitere Marken  Alle weiteren Marken sind Eigentum der jeweiligen Rechteinhaber und werden hiermit anerkannt.  Marken, die nicht Rockwell Automation geh\u00f6ren, sind Eigentum ihrer jeweiligen Inhaber.  Gew\u00e4hrleistung  Die Gew\u00e4hrleistung f\u00fcr dieses Produkt gilt gem\u00e4\u00df der Produktlizenz. Die Leistung des Produkts kann durch Systemkonfiguration, die ausgef\u00fchrte Anwendung, Bediener-Control, Wartung und weitere Faktoren beeinflusst werden. Rockwell Automation ist f\u00fcr diese Faktoren nicht verantwortlich. Die Anweisungen in diesem Dokument decken nicht alle Details oder Variationen im Equipment, Vorgang oder der beschriebenen Prozesse ab, sie enthalten auch keine Anweisungen f\u00fcr jede m\u00f6gliche Eventualit\u00e4t, die w\u00e4hrend der Installation, Bedienung oder Wartung auftreten kann. Die Implementierung dieses Produkts kann sich bei verschiedenen Benutzern unterscheiden.  Dieses Dokument ist zum Zeitpunkt der Ver\u00f6ffentlichung des Produkts g\u00fcltig, jedoch kann sich die gelieferte Software seit der Ver\u00f6ffentlichung ver\u00e4ndert haben. Rockwell Automation Inc. beh\u00e4lt sich das Recht vor, die Informationen in diesem Dokument oder der Software jederzeit ohne Vorank\u00fcndigung zu \u00e4ndern. Es liegt in Ihrer Verantwortung, die aktuellsten Informationen, die durch Rockwell zur Verf\u00fcgung gestellt werden, f\u00fcr die Installation oder den Gebrauch des Produkts zu verwenden.  Wenden Sie sich an Rockwell Automation  Telefonnummer des Kunden-Supports: 1.888.382.1583  Online-Support &#8211; http://www.rockwellautomation.com/support/  "
  }
]
; return json; };
