function search_db_content(){ var json = 
[
  {
    "id": 1,
    "title": "Registra",
    "url": "284567.htm",
    "text": "Registrarsi per gli aggiornamenti utilizzando la Compatibilit\u00e0 del prodotto e il Centro di download  Per registrarsi per ricevere gli aggiornamenti del prodotto Rockwell Automation, ad esempio gli aggiornamenti firmware e i roll-up delle patch, fare riferimento a Compatibilit\u00e0 del prodotto e il Centro di download. Fare clic sull'icona @ Sottoscrizioni per sottoscrivere le notifiche specifiche del prodotto.  Registrarsi agli aggiornamenti della knowledgebase  La Knowledgebase di Rockwell Automation fornisce informazioni supplementari sugli ultimi aggiornamenti del prodotto e informazioni sulle patch.  Per ricevere notifiche su prodotti specifici, seguire le istruzioni riportate nell'ID documento della knowledge base: PN27 - Subscribing to Product Safety Advisory (PSA) or Product Notice (PN) Notifications.  Per ricevere una notifica via email quando l'elenco di aggiornamenti e patch viene aggiornato, selezionare Sottoscrivi aggiornamenti nella parte superiore dell'ID documento della knowledge base: QA57432 - Elenco principale di tutti gli indici delle patch disponibili.  Vedere anche  Informazioni legali  "
  },
  {
    "id": 2,
    "title": "Informazioni legali",
    "url": "196866.htm",
    "text": "Informazioni sul copyright  Copyright &copy; 2020 Rockwell Automation Technologies, Inc. Tutti i diritti riservati. Stampato negli Stati Uniti.  Questo documento e i prodotti software Rockwell Software correlati sono protetti da copyright di Rockwell Automation Technologies, Inc. La riproduzione e/o distribuzione senza previo consenso scritto da parte di Rockwell Automation Technologies, Inc. \u00e8 severamente vietata. Per ulteriori informazioni, fare riferimento al contratto di licenza.  Contratto di licenza con l'utente finale (EULA)  \u00c8 possibile visualizzare il Contratto di licenza con l'utente finale (\"EULA\") di Rockwell Automation aprendo il file License.rtf che si trova nella cartella di installazione del prodotto sul disco rigido.  Altre licenze  FieldCare SFE500 \u00e8 Endress + Hauser AG  Informazioni sui marchi  Allen-Bradley, Rockwell Automation e Rockwell Software sono marchi di Rockwell Automation, Inc.  Qualsiasi altro software o hardware Rockwell Automation non menzionato qui rappresenta anch'esso un marchio, registrato o di altro tipo, di Rockwell Automation, Inc.  Altri marchi  Tutti gli altri marchi sono di propriet\u00e0 dei rispettivi detentori e qui riconosciuti.  I marchi che non appartengono a Rockwell Automation sono di propriet\u00e0 delle rispettive societ\u00e0  Garanzia  Questo prodotto \u00e8 garantito in base alla relativa licenza. Le prestazioni del prodotto possono essere influenzate dalla configurazione del sistema, dall'applicazione in esecuzione, dal controllo dell'operatore, dallo stato di manutenzione e da altri fattori correlati. Rockwell Automation non \u00e8 responsabile di questi fattori interferenti. Le istruzioni contenute in questo documento non coprono tutti i dettagli o le variazioni dell'attrezzatura, della procedura o del processo descritto, n\u00e9 forniscono indicazioni su come affrontare ogni possibile contingenza durante l'installazione, il funzionamento o la manutenzione. L'implementazione di questo prodotto pu\u00f2 variare in base all'utente.  Questo documento \u00e8 aggiornato al momento del rilascio del prodotto; tuttavia, il software correlato potrebbe essere stato modificato dopo il rilascio. Rockwell Automation, Inc. si riserva il diritto di modificare le informazioni contenute in questo documento o nel software in qualsiasi momento e senza preavviso. \u00c8 responsabilit\u00e0 dell'utente procurarsi le informazioni pi\u00f9 recenti disponibili da Rockwell al momento dell'installazione o dell'utilizzo di questo prodotto.  Contatta Rockwell Automation  Telefono del supporto clienti: 1.888.382.1583  Supporto online: http://www.rockwellautomation.com/support/  "
  }
]
; return json; };
