function search_db_content(){ var json = 
[
  {
    "id": 1,
    "title": "S'inscrire",
    "url": "284567.htm",
    "text": "S'inscrire pour recevoir les mises \u00e0 jour en utilisant le Centre de compatibilit\u00e9 et de t\u00e9l\u00e9chargement de produit  Pour vous inscrire afin de recevoir les mises \u00e0 jour du produit Rockwell Automation, ainsi que les correctifs cumul\u00e9s, rendez-vous dans le Centre de compatibilit\u00e9 et de t\u00e9l\u00e9chargement de produit. Cliquez sur l'ic\u00f4ne @ Abonnements pour vous abonner aux notifications concernant des produits sp\u00e9cifiques.  Inscrivez-vous pour recevoir les mises \u00e0 jour de la base de connaissances  La base de connaissances de Rockwell Automation fournit des informations suppl\u00e9mentaires sur les mises \u00e0 jour les plus r\u00e9centes du produit et des informations sur les correctifs.  Pour recevoir des notifications sur des produits sp\u00e9cifiques, suivez les instructions fournies dans l'ID du document de la base de connaissances: \u00ab\u00a0PN27 - Subscribing to Product Safety Advisory (PSA) or Product Notice (PN) Notifications\u00a0\u00bb.  Pour recevoir une notification par courrier \u00e9lectronique lorsque la liste des mises \u00e0 jours et des correctifs est mise \u00e0 jour, s\u00e9lectionnez S'abonner aux mises \u00e0 jour en haut de l'ID de document de la base de connaissances: QA57432 - Liste de r\u00e9f\u00e9rence de tous les TOC de correctifs.  Voir \u00e9galement  Mentions l\u00e9gales  "
  },
  {
    "id": 2,
    "title": "Mentions l\u00e9gales",
    "url": "196866.htm",
    "text": "Avis de copyright  Copyright &copy; 2020 Rockwell Automation Technologies, Inc. All Rights Reserved. Printed in USA.  This document and any accompanying Rockwell Software products are copyrighted by Rockwell Automation Technologies, Inc. Any reproduction and/or distribution without prior written consent from Rockwell Automation Technologies, Inc. is strictly prohibited. Please refer to the license agreement for details.  Contrat de licence utilisateur final (CLUF)  Vous pouvez afficher le Contrat de Licence Utilisateur Final (\u00ab\u00a0CLUF\u00a0\u00bb) de Rockwell Automation en ouvrant le fichier License.rtf situ\u00e9 dans le dossier d'installation du produit sur votre disque dur.  Autres licences  FieldCare SFE500 est une marque de Endress + Hauser AG  Marques  Allen-Bradley, Rockwell Automation et Rockwell Software sont des marques commerciales de Rockwell Automation, Inc.  Tout logiciel ou mat\u00e9riel Rockwell Automation non mentionn\u00e9 ici est \u00e9galement une marque commerciale, d\u00e9pos\u00e9e ou non, de Rockwell Automation , Inc.  Autres marques  Toutes les autres marques utilis\u00e9es dans ce document appartiennent \u00e0 leurs propri\u00e9taires respectifs et sont reconnues en tant que telles par la pr\u00e9sente.  Les marques commerciales n'appartenant pas \u00e0 Rockwell Automation sont la propri\u00e9t\u00e9 de leurs soci\u00e9t\u00e9s respectives  Garantie  Ce produit est garanti conform\u00e9ment aux termes du contrat de licence. La configuration syst\u00e8me, l'application ex\u00e9cut\u00e9e, le contr\u00f4le des op\u00e9rateurs, la maintenance et d'autres facteurs connexes sont susceptibles d'avoir une incidence sur les performances du produit. Rockwell Automation n'est pas responsable de ces facteurs intervenant. Les instructions contenues dans ce document ne pr\u00e9tendent pas traiter tous les d\u00e9tails ou variantes concernant l'\u00e9quipement, les proc\u00e9dures ou les processus d\u00e9crits, ni fournir des indications s'appliquant \u00e0 tous les cas de figure qu'il est possible de rencontrer au cours de l'installation, du fonctionnement ou de la maintenance du produit. La mise en \u0153uvre du produit peut varier selon les utilisateurs.  Ce document est le dernier en date au moment de la diffusion du produit\u00a0; le logiciel qui l'accompagne peut cependant avoir \u00e9t\u00e9 modifi\u00e9 depuis la diffusion. Rockwell Automation, Inc. se r\u00e9serve le droit de modifier sans pr\u00e9avis toute information pr\u00e9sente dans ce document ou dans le logiciel. Vous \u00eates seul responsable de l'obtention des informations les plus \u00e0 jour disponibles, aupr\u00e8s de Rockwell, lors de l'installation ou de l'utilisation de ce produit.  Contacter Rockwell Automation  Num\u00e9ro de t\u00e9l\u00e9phone de l'assistance client\u00e8le\u00a0: 1.888.382.1583  Support en ligne &#8212; http://www.rockwellautomation.com/support/  "
  }
]
; return json; };
